### Auto MPG Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# load the dataset
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
auto_mpg = fetch_ucirepo(id=9) 
  
# data (as pandas dataframes) 
X = auto_mpg.data.features 
y = auto_mpg.data.targets 
  
# metadata 
print(auto_mpg.metadata) 
  
# variable information 
print(auto_mpg.variables)

{'uci_id': 9, 'name': 'Auto MPG', 'repository_url': 'https://archive.ics.uci.edu/dataset/9/auto+mpg', 'data_url': 'https://archive.ics.uci.edu/static/public/9/data.csv', 'abstract': 'Revised from CMU StatLib library, data concerns city-cycle fuel consumption', 'area': 'Other', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 398, 'num_features': 7, 'feature_types': ['Real', 'Categorical', 'Integer'], 'demographics': [], 'target_col': ['mpg'], 'index_col': ['car_name'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1993, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5859H', 'creators': ['R. Quinlan'], 'intro_paper': None, 'additional_info': {'summary': 'This dataset is a slightly modified version of the dataset provided in the StatLib library.  In line with the use by Ross Quinlan (1993) in predicting the attribute "mpg", 8 of the original instances were removed because they had unknown values for the "mpg" attribute.  The original dataset is available in the file "auto-mpg.data-original".\r\n\r\n"The data concerns city-cycle fuel consumption in miles per gallon, to be predicted in terms of 3 multivalued discrete and 5 continuous attributes." (Quinlan, 1993)', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '    1. mpg:           continuous\r\n    2. cylinders:     multi-valued discrete\r\n    3. displacement:  continuous\r\n    4. horsepower:    continuous\r\n    5. weight:        continuous\r\n    6. acceleration:  continuous\r\n    7. model year:    multi-valued discrete\r\n    8. origin:        multi-valued discrete\r\n    9. car name:      string (unique for each instance)', 'citation': None}}
           name     role         type demographic description units  \
0  displacement  Feature   Continuous        None        None  None
1           mpg   Target   Continuous        None        None  None
2     cylinders  Feature      Integer        None        None  None
3    horsepower  Feature   Continuous        None        None  None
4        weight  Feature   Continuous        None        None  None
5  acceleration  Feature   Continuous        None        None  None
6    model_year  Feature      Integer        None        None  None
7        origin  Feature      Integer        None        None  None
8      car_name       ID  Categorical        None        None  None

  missing_values
0             no
1             no
2             no
3            yes
4             no
5             no
6             no
7             no
8             no

In [3]:
X['horsepower'].value_counts().head(1)

horsepower
150.0    22
Name: count, dtype: int64

In [4]:
X['horsepower'].describe()

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [5]:
y.head()

    mpg
0  18.0
1  15.0
2  18.0
3  16.0
4  17.0

In [6]:
X.head()

,displacement,cylinders,horsepower,weight,acceleration,model_year,origin
0,307.0,8,130.0,3504,12.0,70,1
1,350.0,8,165.0,3693,11.5,70,1
2,318.0,8,150.0,3436,11.0,70,1
3,304.0,8,150.0,3433,12.0,70,1
4,302.0,8,140.0,3449,10.5,70,1

In [7]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 21.9 KB

In [8]:
# concatenate temporarily
df = pd.concat([X,y], axis=1)
df.head()

,displacement,cylinders,horsepower,weight,acceleration,model_year,origin,mpg
0,307.0,8,130.0,3504,12.0,70,1,18.0
1,350.0,8,165.0,3693,11.5,70,1,15.0
2,318.0,8,150.0,3436,11.0,70,1,18.0
3,304.0,8,150.0,3433,12.0,70,1,16.0
4,302.0,8,140.0,3449,10.5,70,1,17.0

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=254)

X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 318 entries, 47 to 326
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  318 non-null    float64
 1   cylinders     318 non-null    int64
 2   horsepower    313 non-null    float64
 3   weight        318 non-null    int64
 4   acceleration  318 non-null    float64
 5   model_year    318 non-null    int64
 6   origin        318 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 19.9 KB

In [10]:
# #instantiate

# lr = LinearRegression()

# lr.fit(X_train, y_train)

In [11]:
X_train.columns

Index(['displacement', 'cylinders', 'horsepower', 'weight', 'acceleration',
       'model_year', 'origin'],
      dtype='object')

In [12]:
X_train.describe()

,displacement,cylinders,horsepower,weight,acceleration,model_year,origin
count,318.000000,318.000000,313.000000,318.000000,318.000000,318.000000,318.000000
mean,195.504717,5.471698,105.076677,2977.905660,15.566667,75.933962,1.562893
std,104.672981,1.699179,39.146182,845.251187,2.747667,3.744023,0.798741
min,68.000000,3.000000,46.000000,1613.000000,8.000000,70.000000,1.000000
25%,105.000000,4.000000,78.000000,2236.750000,14.000000,73.000000,1.000000
50%,151.000000,4.000000,95.000000,2822.500000,15.500000,76.000000,1.000000
75%,292.000000,8.000000,129.000000,3629.000000,17.175000,79.000000,2.000000
max,455.000000,8.000000,230.000000,4997.000000,23.700000,82.000000,3.000000

In [13]:
threshold =  len(df)*.95

threshold

378.09999999999997

In [14]:
df_cleaned =  df.dropna(thresh=threshold, axis=1)

df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [16]:
# # filling in a null entry
# median_horsepower = df_cleaned['horsepower'].median()

# median_df['horsepower'] =  df_cleaned['horsepower'].fillna(median_horsepower)

# median_df.isnull().count()

In [19]:
# median_df.info()

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [ ]:
# # filling in a null entry
# # Calculate mean horsepower
# mean_horsepower = df_cleaned['horsepower'].mean()

# # Fill missing values with the mean and create a new DataFrame copy
# mean_df = df_cleaned.copy()
# mean_df['horsepower'] = df_cleaned['horsepower'].fillna(mean_horsepower)

# # Count remaining nulls
# null_count = mean_df['horsepower'].isnull().sum()
# print(null_count)

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = cleaned_df.drop(columns=['mpg'], axis=1)
y = cleaned_df['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=254)

X_train.info()

NameError: name 'cleaned_df' is not defined

In [21]:
#instantiate

lr = LinearRegression()

lr.fit(X_train, y_train)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values